/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, clerkId: {
                    name: "clerkId",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, userCourses: {
                    name: "userCourses",
                    type: "UserCourse",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, clerkId: {
                    name: "clerkId",
                    fields: ["clerkId"]
                },
            }
            ,
        }
        ,
        language: {
            name: 'Language', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, nativeCourses: {
                    name: "nativeCourses",
                    type: "Course",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'nativeLanguage',
                }, targetCourses: {
                    name: "targetCourses",
                    type: "Course",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'targetLanguage',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            }
            ,
        }
        ,
        course: {
            name: 'Course', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, nativeLanguage: {
                    name: "nativeLanguage",
                    type: "Language",
                    isDataModel: true,
                    backLink: 'nativeCourses',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "nativeLanguageId" },
                }, nativeLanguageId: {
                    name: "nativeLanguageId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'nativeLanguage',
                }, targetLanguage: {
                    name: "targetLanguage",
                    type: "Language",
                    isDataModel: true,
                    backLink: 'targetCourses',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "targetLanguageId" },
                }, targetLanguageId: {
                    name: "targetLanguageId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'targetLanguage',
                }, outcome: {
                    name: "outcome",
                    type: "String",
                    isOptional: true,
                }, level: {
                    name: "level",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, userCourses: {
                    name: "userCourses",
                    type: "UserCourse",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'course',
                }, lessons: {
                    name: "lessons",
                    type: "Lesson",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'course',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        userCourse: {
            name: 'UserCourse', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'userCourses',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, course: {
                    name: "course",
                    type: "Course",
                    isDataModel: true,
                    backLink: 'userCourses',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "courseId" },
                }, courseId: {
                    name: "courseId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'course',
                }, role: {
                    name: "role",
                    type: "UserCourseRole",
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId_courseId_role: {
                    name: "userId_courseId_role",
                    fields: ["userId", "courseId", "role"]
                },
            }
            ,
        }
        ,
        lesson: {
            name: 'Lesson', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, type: {
                    name: "type",
                    type: "String",
                }, scenarioContext: {
                    name: "scenarioContext",
                    type: "String",
                }, lessonJson: {
                    name: "lessonJson",
                    type: "Json",
                    isOptional: true,
                }, audioUrl: {
                    name: "audioUrl",
                    type: "String",
                    isOptional: true,
                }, audioUrls: {
                    name: "audioUrls",
                    type: "String",
                    isArray: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, segments: {
                    name: "segments",
                    type: "Json",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, course: {
                    name: "course",
                    type: "Course",
                    isDataModel: true,
                    backLink: 'lessons',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "courseId" },
                }, courseId: {
                    name: "courseId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'course',
                }, progress: {
                    name: "progress",
                    type: "ProgressStatus",
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
    }
    ,
    authModel: 'User'
};
export default metadata;
