/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, LessonCatalog } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateLessonCatalog(options?: Omit<(UseMutationOptions<(LessonCatalog | undefined), DefaultError, Prisma.LessonCatalogCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogCreateArgs, DefaultError, LessonCatalog, true>('LessonCatalog', 'POST', `${endpoint}/lessonCatalog/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyLessonCatalog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LessonCatalogCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('LessonCatalog', 'POST', `${endpoint}/lessonCatalog/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyLessonCatalog<TArgs extends Prisma.LessonCatalogFindManyArgs, TQueryFnData = Array<Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLessonCatalog<TArgs extends Prisma.LessonCatalogFindManyArgs, TQueryFnData = Array<Prisma.LessonCatalogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findMany`, args, options, fetch);
}

export function useSuspenseFindManyLessonCatalog<TArgs extends Prisma.LessonCatalogFindManyArgs, TQueryFnData = Array<Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyLessonCatalog<TArgs extends Prisma.LessonCatalogFindManyArgs, TQueryFnData = Array<Prisma.LessonCatalogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findMany`, args, options, fetch);
}

export function useFindUniqueLessonCatalog<TArgs extends Prisma.LessonCatalogFindUniqueArgs, TQueryFnData = Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueLessonCatalog<TArgs extends Prisma.LessonCatalogFindUniqueArgs, TQueryFnData = Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findUnique`, args, options, fetch);
}

export function useFindFirstLessonCatalog<TArgs extends Prisma.LessonCatalogFindFirstArgs, TQueryFnData = Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstLessonCatalog<TArgs extends Prisma.LessonCatalogFindFirstArgs, TQueryFnData = Prisma.LessonCatalogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/findFirst`, args, options, fetch);
}

export function useUpdateLessonCatalog(options?: Omit<(UseMutationOptions<(LessonCatalog | undefined), DefaultError, Prisma.LessonCatalogUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogUpdateArgs, DefaultError, LessonCatalog, true>('LessonCatalog', 'PUT', `${endpoint}/lessonCatalog/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyLessonCatalog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LessonCatalogUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('LessonCatalog', 'PUT', `${endpoint}/lessonCatalog/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertLessonCatalog(options?: Omit<(UseMutationOptions<(LessonCatalog | undefined), DefaultError, Prisma.LessonCatalogUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogUpsertArgs, DefaultError, LessonCatalog, true>('LessonCatalog', 'POST', `${endpoint}/lessonCatalog/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteLessonCatalog(options?: Omit<(UseMutationOptions<(LessonCatalog | undefined), DefaultError, Prisma.LessonCatalogDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogDeleteArgs, DefaultError, LessonCatalog, true>('LessonCatalog', 'DELETE', `${endpoint}/lessonCatalog/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LessonCatalog, Prisma.LessonCatalogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyLessonCatalog(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LessonCatalogDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LessonCatalogDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('LessonCatalog', 'DELETE', `${endpoint}/lessonCatalog/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LessonCatalogDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LessonCatalogDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LessonCatalogDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateLessonCatalog<TArgs extends Prisma.LessonCatalogAggregateArgs, TQueryFnData = Prisma.GetLessonCatalogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateLessonCatalog<TArgs extends Prisma.LessonCatalogAggregateArgs, TQueryFnData = Prisma.GetLessonCatalogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/aggregate`, args, options, fetch);
}

export function useGroupByLessonCatalog<TArgs extends Prisma.LessonCatalogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LessonCatalogGroupByArgs['orderBy'] } : { orderBy?: Prisma.LessonCatalogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LessonCatalogGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.LessonCatalogGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.LessonCatalogGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.LessonCatalogGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LessonCatalogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByLessonCatalog<TArgs extends Prisma.LessonCatalogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LessonCatalogGroupByArgs['orderBy'] } : { orderBy?: Prisma.LessonCatalogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LessonCatalogGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.LessonCatalogGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.LessonCatalogGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.LessonCatalogGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LessonCatalogGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/groupBy`, args, options, fetch);
}

export function useCountLessonCatalog<TArgs extends Prisma.LessonCatalogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LessonCatalogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/count`, args, options, fetch);
}

export function useSuspenseCountLessonCatalog<TArgs extends Prisma.LessonCatalogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LessonCatalogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LessonCatalogCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LessonCatalog', `${endpoint}/lessonCatalog/count`, args, options, fetch);
}

export function useCheckLessonCatalog<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; nativeLanguageId?: string; targetLanguageId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('LessonCatalog', `${endpoint}/lessonCatalog/check`, args, options, fetch);
}
